export const adminUsers = [
  {
    id: "1",
    name: "Abdul Khalid",
    email: "ice40125@gmail.com",
    password: "admin123",
    role: "admin",
  },
  {
    id: "2",
    name: "John Doe",
    email: "john@sgtu.edu.in",
    password: "john123",
    role: "manager",
  },
  {
    id: "3",
    name: "Jane Smith",
    email: "jane@sgtu.edu.in",
    password: "jane123",
    role: "staff",
  },
  {
    id: "4",
    name: "Robert Johnson",
    email: "robert@sgtu.edu.in",
    password: "robert123",
    role: "staff",
  },
  {
    id: "5",
    name: "Emily Davis",
    email: "emily@sgtu.edu.in",
    password: "emily123",
    role: "staff",
  },
  {
    id: "6",
    name: "Michael Wilson",
    email: "michael@sgtu.edu.in",
    password: "michael123",
    role: "staff",
  },
  {
    id: "7",
    name: "Sarah Brown",
    email: "sarah@sgtu.edu.in",
    password: "sarah123",
    role: "staff",
  },
  {
    id: "8",
    name: "David Miller",
    email: "david@sgtu.edu.in",
    password: "david123",
    role: "staff",
  },
  {
    id: "9",
    name: "Lisa Taylor",
    email: "lisa@sgtu.edu.in",
    password: "lisa123",
    role: "staff",
  },
  {
    id: "10",
    name: "James Anderson",
    email: "james@sgtu.edu.in",
    password: "james123",
    role: "staff",
  },
]
